### ISSUE TITLE
English language

### ISSUE THREAD

**Issue by S0lRaK** [S0lRaK/Sobbles#4]
Game texts in English.

**Comment by odelrio** [comment]
A traducir:
- Griego
- Iniciar
- Puntuación
- Supervivencia
- Contrarreloj
- Vidas
- Puntuación
- ¿Listo?
- 3... 2... 1...
- Buena suerte
- Fin de la partida
- Pausa
- Reanudar
- Explota todas las burbujas que puedas en un minuto
- Explota las burbujas antes de que se escapen

**Comment by S0lRaK** [comment]
1. **Game title**
2. **Language selection**
   - Català
   - Castellano
   - English
   - _ελληνικά_
3. **Mode selection**
   - Time Trial
     - Explode all bubbles you can in a minute
   - Survival
     - Explode all bubbles you can before they escape
   - Start
4. **Preparing to play**
   - Ready?
   - 3... 2... 1...
   - Good luck!
5. **Playing**
   - Lives
   - Remaining time / Time (_according to the Mode selected_)
   - Score
   - Pause
6. **Paused**
   - Lives
   - Remaining time / Time (_according to the Mode selected_)
   - Score
   - Resume
7. **End of the game**
   - Remaining time / Time (_according to the Mode selected_)
   - Score
   - Retry
   - Mode selection
   - _Language selection_
