### ISSUE TITLE
Catalan language

### ISSUE THREAD

**Issue by S0lRaK** [S0lRaK/Sobbles#6]
Game texts in Catalan.

**Comment by odelrio** [comment]
A traducir:
- Griego
- Iniciar
- Puntuación
- Supervivencia
- Contrarreloj
- Vidas
- Puntuación
- ¿Listo?
- 3... 2... 1...
- Buena suerte
- Fin de la partida
- Pausa
- Reanudar
- Explota todas las burbujas que puedas en un minuto
- Explota las burbujas antes de que se escapen

**Comment by S0lRaK** [comment]
1. **Game title**
2. **Language selection**
   - Català
   - Castellano
   - English
   - _ελληνικά_
3. **Mode selection**
   - Contrarellotge
     - Explota totes les bombolles que puguis en un minut
   - Supervivència
     - Explota totes les bombolles que puguis abans de que s'escapin
   - Iniciar
4. **Preparing to play**
   - Preparat?
   - 3... 2... 1...
   - Bona sort!
5. **Playing**
   - Vides
   - Temps restant / Temps (_according to the Mode selected_)
   - Puntuació
   - Pausa
6. **Paused**
   - Vides
   - Temps restant / Temps (_according to the Mode selected_)
   - Puntuació
   - Reprendre
7. **Final de la partida**
   - Temps restant / Temps (_according to the Mode selected_)
   - Puntuació
   - Supera't! (_Retry_)
   - Sel·lecció de Mode
   - _Sel·lecció d'Idioma_
