### ISSUE TITLE
Greek language

### ISSUE THREAD

**Issue by S0lRaK** [S0lRaK/Sobbles#7]

**Comment by odelrio** [comment]
Tenemos una fuente con los caracteres griegos: https://github.com/S0lRaK/Android-bubble-game/tree/master/documents/BubblesOriol/Assets/Typography

A traducir:
- Griego
- Iniciar
- Puntuación
- Supervivencia
- Contrarreloj
- Vidas
- Puntuación
- ¿Listo?
- 3... 2... 1...
- Buena suerte
- Fin de la partida
- Pausa
- Reanudar
- Explota todas las burbujas que puedas en un minuto
- Explota las burbujas antes de que se escapen

**Comment by odelrio** [comment]
Griego = Ελληνικά
Iniciar = Εκκίνηση
Puntuación = Βαθμολογία
Supervivencia = Επιβίωση
Contrarreloj = Δοκιμή ενάντια στο χρόνο 
Vidas = Ζωές 
¿Listo? = Έτοιμος?
3... 2... 1… = ( είστε σοβαροί? )
Buena suerte = Καλή τύχη
Fin de la partida = Τέλος της παρτίδας
Pausa = Παύση
Reanudar = Επαννεκίνηση
Explota todas las burbujas que puedas en un minuto = Κάνε όσο πιο πολλές φούσκες μπορείς, να εκραγούν, μέσα σε ένα λεπτό.
Explota las burbujas antes de que se escapen = Κάνε τις φούσκες να εκραγούν πριν αυτές σου ξεφύγουνε.
